In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

**Exploración inicial**

In [2]:
df_INAH_visitas = pd.read_csv('../data/raw/INAH_visitantes_museos_general.csv')
pd.set_option('display.max_columns', None)
df_INAH_visitas.head(5)

,anio,estado,clave_siinah,recinto,enero_nac,enero_ext,febrero_nac,febrero_ext,marzo_nac,marzo_ext,abril_nac,abril_ext,mayo_nac,mayo_ext,junio_nac,junio_ext,julio_nac,julio_ext,agosto_nac,agosto_ext,septiembre_nac,septiembre_ext,octubre_nac,octubre_ext,noviembre_nac,noviembre_ext,diciembre_nac,diciembre_ext
0,2025,Aguascalientes,2300100,Museo Regional de Historia de Aguascalientes,967,33,1721,27,1658,29,3726,61,2076,21,1378,50,1900,76,1571,46,1643,41,2959,66,3349,61,1660,61
1,2025,Baja California,2400100,"Museo Histórico Regional, Ex Cuartel de la Com...",1304,410,997,414,1932,292,1755,186,2544,409,3240,386,2100,511,2852,480,1649,132,3774,478,1784,516,1159,832
2,2025,Baja California Sur,2300200,Museo Regional de Antropología e Historia de B...,2266,983,1868,1101,2635,806,2337,544,2004,348,2009,547,2188,476,1040,567,940,346,2090,491,1969,515,1214,737
3,2025,Baja California Sur,2400200,Museo de Las Misiones Jesuíticas,659,179,887,474,798,551,1503,431,547,42,675,43,828,17,547,23,324,14,589,325,712,302,887,470
4,2025,Baja California Sur,2400300,Museo de las Pinturas Rupestres de San Ignacio,36,0,73,4,0,0,356,0,0,0,10,0,177,93,27,0,0,0,25,0,130,18,119,0

In [3]:
df_INAH_visitas.info()

<class 'pandas.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   anio            3008 non-null   int64
 1   estado          3008 non-null   str
 2   clave_siinah    3008 non-null   int64
 3   recinto         3008 non-null   str
 4   enero_nac       3008 non-null   int64
 5   enero_ext       3008 non-null   int64
 6   febrero_nac     3008 non-null   int64
 7   febrero_ext     3008 non-null   int64
 8   marzo_nac       3008 non-null   int64
 9   marzo_ext       3008 non-null   int64
 10  abril_nac       3008 non-null   int64
 11  abril_ext       3008 non-null   int64
 12  mayo_nac        3008 non-null   int64
 13  mayo_ext        3008 non-null   int64
 14  junio_nac       3008 non-null   int64
 15  junio_ext       3008 non-null   int64
 16  julio_nac       3008 non-null   int64
 17  julio_ext       3008 non-null   int64
 18  agosto_nac      3008 non-null   int64
 19  agosto_ext      3008 non-null   int64
 20  septiembre_nac  3008 non-null   int64
 21  septiembre_ext  3008 non-null   int64
 22  octubre_nac     3008 non-null   int64
 23  octubre_ext     3008 non-null   int64
 24  noviembre_nac   3008 non-null   int64
 25  noviembre_ext   3008 non-null   int64
 26  diciembre_nac   3008 non-null   int64
 27  diciembre_ext   3008 non-null   int64
dtypes: int64(26), str(2)
memory usage: 658.1 KB

El conjunto de datos cuenta con 3008 registros/filas y 28 columnas(2 str y 26 int).

In [4]:
cantidad_nulos = df_INAH_visitas.isnull().sum()
print(f'Cantidad de valores nulos: {cantidad_nulos}')

Cantidad de valores nulos: anio              0
estado            0
clave_siinah      0
recinto           0
enero_nac         0
enero_ext         0
febrero_nac       0
febrero_ext       0
marzo_nac         0
marzo_ext         0
abril_nac         0
abril_ext         0
mayo_nac          0
mayo_ext          0
junio_nac         0
junio_ext         0
julio_nac         0
julio_ext         0
agosto_nac        0
agosto_ext        0
septiembre_nac    0
septiembre_ext    0
octubre_nac       0
octubre_ext       0
noviembre_nac     0
noviembre_ext     0
diciembre_nac     0
diciembre_ext     0
dtype: int64

In [5]:
cantidad_duplicados = df_INAH_visitas.duplicated().sum()
print(f'Cantidad de registros/filas duplicadas: \n{cantidad_duplicados}')

Cantidad de registros/filas duplicadas:
0

No se identificaron valores nulos y duplicados.

In [6]:
annios = df_INAH_visitas['anio'].value_counts().sort_index(ascending=False)
print(annios)

anio
2025    104
2024    103
2023    101
2022    101
2021    101
2020    101
2019    101
2018    101
2017    101
2016     99
2015    102
2014    100
2013    100
2012    100
2011     99
2010     98
2009     99
2008    100
2007    101
2006     97
2005     98
2004     99
2003     99
2002    101
2001     95
2000     95
1999    103
1998    103
1997    103
1996    103
Name: count, dtype: int64

In [7]:
estados = df_INAH_visitas['estado'].value_counts().sort_index(ascending=True)
print(estados)

estado
Aguascalientes          30
Baja California         30
Baja California Sur    118
Campeche               120
Chiapas                120
Chihuahua               30
Ciudad de México       270
Coahuila                30
Colima                  30
Estado de México       236
Guanajuato             230
Guerrero                90
Hidalgo                136
Jalisco                120
Michoacán              150
Morelos                121
Nayarit                 60
Nuevo León              30
Oaxaca                 214
Puebla                 345
Querétaro               30
Quintana Roo            25
San Luis Potosí         30
Sinaloa                 28
Sonora                  30
Tabasco                 30
Tamaulipas              30
Tlaxcala                30
Veracruz               172
Yucatán                 63
Zacatecas               30
Name: count, dtype: int64

In [29]:
siinah = df_INAH_visitas['clave_siinah'].value_counts()
siinah

clave_siinah
4100015    39
2402000    38
4100016    37
2301000    31
4100017    31
           ..
2404000    23
2401600    20
4200004    10
4200002     4
0           3
Name: count, Length: 103, dtype: int64

In [16]:
clave_siianh = df_INAH_visitas['clave_siinah']
for clave in clave_siianh:
    if len(str(clave)) < 7:
        print(clave)

0
0
0

In [18]:
nombre_museo = df_INAH_visitas['recinto'].value_counts()
nombre_museo

<bound method IndexOpsMixin.value_counts of 0            Museo Regional de Historia de Aguascalientes
1       Museo Histórico Regional, Ex Cuartel de la Com...
2       Museo Regional de Antropología e Historia de B...
3                        Museo de Las Misiones Jesuíticas
4          Museo de las Pinturas Rupestres de San Ignacio
                              ...
3003    Museo de Sitio de Tres Zapotes con Zona Arqueo...
3004                                   Museo de Palmillas
3005           Museo Regional de Yucatán "Palacio Cantón"
3006           Pinacoteca del Estado "Juan Gamboa Guzmán"
3007                                   Museo de Guadalupe
Name: recinto, Length: 3008, dtype: str>

In [20]:
registros_clave_siinah_0 = df_INAH_visitas[df_INAH_visitas['clave_siinah'] == 0]
registros_clave_siinah_0

,anio,estado,clave_siinah,recinto,enero_nac,enero_ext,febrero_nac,febrero_ext,marzo_nac,marzo_ext,abril_nac,abril_ext,mayo_nac,mayo_ext,junio_nac,junio_ext,julio_nac,julio_ext,agosto_nac,agosto_ext,septiembre_nac,septiembre_ext,octubre_nac,octubre_ext,noviembre_nac,noviembre_ext,diciembre_nac,diciembre_ext
86,2025,Quintana Roo,0,Museo de la Costa Oriental,7452,3461,8562,5749,6942,3625,6942,3625,6804,2581,5283,2020,10214,3407,10276,3472,6198,2194,6711,2921,6635,3704,7325,3697
101,2025,Yucatán,0,Gran Museo de Chichén Itzá,392,310,442,229,532,324,389,208,330,173,258,161,384,174,523,286,288,75,409,217,684,472,461,399
205,2024,Yucatán,0,Gran Museo de Chichén Itzá,0,0,0,0,1099,185,752,102,569,138,449,111,346,103,139,73,78,17,345,87,307,203,482,174

In [23]:
recinto_museo_costa_oriental = df_INAH_visitas[df_INAH_visitas['recinto'] == 'Museo de la Costa Oriental']
recinto_museo_costa_oriental

,anio,estado,clave_siinah,recinto,enero_nac,enero_ext,febrero_nac,febrero_ext,marzo_nac,marzo_ext,abril_nac,abril_ext,mayo_nac,mayo_ext,junio_nac,junio_ext,julio_nac,julio_ext,agosto_nac,agosto_ext,septiembre_nac,septiembre_ext,octubre_nac,octubre_ext,noviembre_nac,noviembre_ext,diciembre_nac,diciembre_ext
86,2025,Quintana Roo,0,Museo de la Costa Oriental,7452,3461,8562,5749,6942,3625,6942,3625,6804,2581,5283,2020,10214,3407,10276,3472,6198,2194,6711,2921,6635,3704,7325,3697

In [28]:
museos_quintana_roo = df_INAH_visitas[df_INAH_visitas['estado'] == 'Quintana Roo']
museos_quintana_roo['recinto'].value_counts()

recinto
Museo Maya de Cancún con Z. A    24
Museo de la Costa Oriental        1
Name: count, dtype: int64

In [25]:
recinto_gran_museo_chichenitza = df_INAH_visitas[df_INAH_visitas['recinto'] == 'Gran Museo de Chichén Itzá']
recinto_gran_museo_chichenitza

,anio,estado,clave_siinah,recinto,enero_nac,enero_ext,febrero_nac,febrero_ext,marzo_nac,marzo_ext,abril_nac,abril_ext,mayo_nac,mayo_ext,junio_nac,junio_ext,julio_nac,julio_ext,agosto_nac,agosto_ext,septiembre_nac,septiembre_ext,octubre_nac,octubre_ext,noviembre_nac,noviembre_ext,diciembre_nac,diciembre_ext
101,2025,Yucatán,0,Gran Museo de Chichén Itzá,392,310,442,229,532,324,389,208,330,173,258,161,384,174,523,286,288,75,409,217,684,472,461,399
205,2024,Yucatán,0,Gran Museo de Chichén Itzá,0,0,0,0,1099,185,752,102,569,138,449,111,346,103,139,73,78,17,345,87,307,203,482,174

In [27]:
museos_yucatan = df_INAH_visitas[df_INAH_visitas['estado'] == 'Yucatán']
museos_yucatan['recinto'].value_counts()

recinto
Museo Regional de Yucatán "Palacio Cantón"    30
Pinacoteca del Estado "Juan Gamboa Guzmán"    30
Gran Museo de Chichén Itzá                     2
Museo de Sitio Ateneo Peninsular               1
Name: count, dtype: int64

In [30]:
museo_x = df_INAH_visitas[df_INAH_visitas['clave_siinah'] == 4100016]
museo_x

,anio,estado,clave_siinah,recinto,enero_nac,enero_ext,febrero_nac,febrero_ext,marzo_nac,marzo_ext,abril_nac,abril_ext,mayo_nac,mayo_ext,junio_nac,junio_ext,julio_nac,julio_ext,agosto_nac,agosto_ext,septiembre_nac,septiembre_ext,octubre_nac,octubre_ext,noviembre_nac,noviembre_ext,diciembre_nac,diciembre_ext
5,2025,Baja California Sur,4100016,Misión de San Francisco Javier,456,593,825,664,838,912,1081,568,818,245,616,259,762,211,1224,241,805,151,671,366,881,368,1347,247
83,2025,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,763,4,239,0,388,0,489,1,321,7,435,2,712,0,546,1,309,0,289,0,367,0,421,1
109,2024,Baja California Sur,4100016,Misión de San Francisco Javier,1486,663,1120,0,904,224,1250,110,406,107,960,167,1382,302,1335,154,516,176,698,372,823,838,884,636
188,2024,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,545,15,381,4,652,0,451,5,303,0,260,0,592,0,482,1,300,0,629,0,359,0,558,9
212,2023,Baja California Sur,4100016,Misión de San Francisco Javier,1546,1179,894,1352,820,1150,1615,887,637,269,507,72,1218,285,1965,221,774,150,733,266,807,275,3794,375
290,2023,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,826,4,642,0,535,0,696,0,405,0,677,0,522,0,458,0,557,0,645,0,644,0,711,15
313,2022,Baja California Sur,4100016,Misión de San Francisco Javier,1261,568,1143,1060,974,1010,1194,412,1042,535,496,135,1114,273,1254,243,1114,273,708,215,954,542,3172,368
391,2022,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,0,0,0,0,615,0,597,8,315,0,523,0,618,7,436,3,327,0,515,0,701,0,599,0
414,2021,Baja California Sur,4100016,Misión de San Francisco Javier,0,0,0,0,303,118,384,43,409,123,486,176,0,0,0,0,0,0,0,0,217,37,1466,320
492,2021,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
515,2020,Baja California Sur,4100016,Misión de San Francisco Javier,2060,248,1278,510,1126,517,0,0,0,0,0,0,0,0,0,0,0,0,1000,124,720,222,819,92
593,2020,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,2237,27,820,13,938,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
616,2019,Baja California Sur,4100016,Misión de San Francisco Javier,957,163,963,547,733,477,675,376,769,179,224,48,1161,235,1455,156,1062,241,1028,589,790,280,4459,214
694,2019,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,2006,45,758,2,547,3,894,11,717,5,788,0,1318,22,1285,11,839,2,1329,4,3124,11,923,1
717,2018,Baja California Sur,4100016,Misión de San Francisco Javier,259,461,737,739,915,636,1440,541,591,563,502,302,1078,156,1251,46,485,11,933,71,453,62,5300,419
795,2018,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,1866,100,1204,22,796,25,1456,55,556,10,975,30,1674,7,1246,10,1113,8,1012,12,1950,4,477,2
818,2017,Baja California Sur,4100016,Misión de San Francisco Javier,534,382,727,987,570,818,297,154,758,128,434,125,861,136,1866,163,625,18,434,34,830,367,5696,547
896,2017,Puebla,4100016,Museo de sitio de Teteles del Santo Nombre con...,1370,0,3061,0,4629,0,7004,1,2958,0,1224,2,2023,4,1459,7,920,0,722,7,661,0,909,51
919,2016,Baja California Sur,4100016,Misión de San Francisco Javier,266,164,232,124,1121,817,1143,279,541,150,378,57,745,180,520,102,326,124,507,117,579,187,5584,569
1018,2015,Baja California Sur,4100016,Misión de San Francisco Javier,240,228,467,752,466,580,1116,489,627,320,198,28,542,120,624,47,356,41,542,120,446,74,4625,371
1120,2014,Baja California Sur,4100016,Misión de San Francisco Javier,248,162,561,525,393,531,581,279,358,184,273,98,226,37,179,23,101,12,179,218,253,343,724,254
1220,2013,Baja California Sur,4100016,Misión de San Francisco Javier,650,62,1098,380,1414,452,1764,294,811,175,775,163,1247,147,671,99,257,29,212,22,315,177,424,257
1320,2012,Baja California Sur,4100016,Misión de San Francisco Javier,667,211,292,366,158,161,1147,185,304,112,180,66,1145,39,791,150,300,66,283,145,681,294,2952,30
1420,2011,Baja California Sur,4100016,Misión de San Francisco Javier,302,55,323,76,148,63,888,242,312,176,273,104,280,134,280,134,222,56,243,87,259,238,581,101
1519,2010,Baja California Sur,4100016,Misión de San Francisco Javier,295,131,544,228,647,387,1327,161,252,63,174,49,125,16,461,146,55,42,180,84,154,71,341,29
1617,2009,Baja California Sur,4100016,Misión de San Francisco Javier,700,219,627,521,445,109,593,239,100,17,572,38,482,27,373,38,287,70,249,76,174,60,1298,95
1716,2008,Baja California Sur,4100016,Misión de San Francisco Javier,949,379,742,644,1276,1506,1184,605,624,146,562,471,877,124,392,74,257,221,338,96,550,161,696,229
1816,2007,Baja California Sur,4100016,Misión de San Francisco Javier,303,366,683,561,530,722,970,405,419,237,342,104,815,108,918,305,429,74,424,184,462,204,4500,250
1917,2006,Baja California Sur,4100016,Misión de San Francisco Javier,382,265,382,265,552,383,808,337,314,174,81,65,550,113,516,315,124,44,191,111,549,266,317,167
2014,2005,Baja California Sur,4100016,Misión de San Francisco Javier,419,291,243,462,633,476,737,252,48,51,241,152,624,156,743,312,84,48,441,130,564,274,247,97
2112,2004,Baja California Sur,4100016,Misión de San Francisco Javier,374,330,264,389,215,367,555,239,149,139,201,108,174,39,146,121,205,81,252,131,346,171,115,78
2211,2003,Baja California Sur,4100016,Misión de San Francisco Javier,733,292,220,300,376,254,614,223,133,164,254,72,228,83,137,66,73,55,99,112,266,142,51,43
2310,2002,Baja California Sur,4100016,Misión de San Francisco Javier,134,122,136,240,392,232,0,0,70,114,87,27,283,51,318,23,141,18,195,96,169,93,57,33
2601,1999,Baja California Sur,4100016,Misión de San Francisco Javier,0,0,65,76,0,0,0,0,70,90,52,23,56,61,100,65,36,23,82,81,45,72,179,201
2704,1998,Baja California Sur,4100016,Misión de San Francisco Javier,90,135,110,145,101,210,316,203,76,92,76,82,81,97,110,201,41,30,51,92,99,110,62,72
2807,1997,Baja California Sur,4100016,Misión de San Francisco Javier,138,300,97,199,208,213,125,154,81,180,55,138,50,75,90,109,19,23,145,175,44,134,55,124
2910,1996,Baja California Sur,4100016,Misión de San Francisco Javier,99,189,101,205,112,40,130,132,105,115,83,45,145,121,0,0,32,47,79,87,81,102,107,129

1. No se identificaron valores faltantes o valores incorrectos en las columnas anios, estados, recintos.
2. Se identificaron 3 calves siinah de un solo digito cuando las demás claves son 7 digitos.
3. Los valores 0 en las columnas de visitas nacionales y extranjeros no son errores, representan total ausencia de visitas por causas como cierre del museo, remodelaciones, cero interes en las excibiciones e inclusive por inseguridad.
4.-Las claves siinah no son identificadores unicos de museso, por lo que son irrelevantes.